///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace aaa
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the aaaRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("5ae4a7da-8dce-4cee-b9d1-e60946e39d2a")]
    public partial class aaaRepository : RepoGenBaseFolder
    {
        static aaaRepository instance = new aaaRepository();
        aaaRepositoryFolders.ExplorerAppFolder _explorer;
        aaaRepositoryFolders.GitCloneAppFolder _gitclone;

        /// <summary>
        /// Gets the singleton class instance representing the aaaRepository element repository.
        /// </summary>
        [RepositoryFolder("5ae4a7da-8dce-4cee-b9d1-e60946e39d2a")]
        public static aaaRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public aaaRepository() 
            : base("aaaRepository", "/", null, 0, false, "5ae4a7da-8dce-4cee-b9d1-e60946e39d2a", ".\\RepositoryImages\\aaaRepository5ae4a7da.rximgres")
        {
            _explorer = new aaaRepositoryFolders.ExplorerAppFolder(this);
            _gitclone = new aaaRepositoryFolders.GitCloneAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5ae4a7da-8dce-4cee-b9d1-e60946e39d2a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("5440dec8-b077-44a0-b049-5382c46e357e")]
        public virtual aaaRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The GitClone folder.
        /// </summary>
        [RepositoryFolder("3f1d1afe-e772-499f-9062-2bd3538a56d0")]
        public virtual aaaRepositoryFolders.GitCloneAppFolder GitClone
        {
            get { return _gitclone; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class aaaRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("5440dec8-b077-44a0-b049-5382c46e357e")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _gitcloneInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "5440dec8-b077-44a0-b049-5382c46e357e", "")
            {
                _gitcloneInfo = new RepoItemInfo(this, "GitClone", "?/?/list[@controlid='1']/listitem[@text='gitClone']", 30000, null, "c8c34b0e-541f-4a47-80f9-4a22e869d2ac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5440dec8-b077-44a0-b049-5382c46e357e")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5440dec8-b077-44a0-b049-5382c46e357e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GitClone item.
            /// </summary>
            [RepositoryItem("c8c34b0e-541f-4a47-80f9-4a22e869d2ac")]
            public virtual Ranorex.ListItem GitClone
            {
                get
                {
                    return _gitcloneInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The GitClone item info.
            /// </summary>
            [RepositoryItemInfo("c8c34b0e-541f-4a47-80f9-4a22e869d2ac")]
            public virtual RepoItemInfo GitCloneInfo
            {
                get
                {
                    return _gitcloneInfo;
                }
            }
        }

        /// <summary>
        /// The GitCloneAppFolder folder.
        /// </summary>
        [RepositoryFolder("3f1d1afe-e772-499f-9062-2bd3538a56d0")]
        public partial class GitCloneAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fermerInfo;

            /// <summary>
            /// Creates a new GitClone  folder.
            /// </summary>
            public GitCloneAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GitClone", "/form[@title='gitClone']", parentFolder, 30000, null, true, "3f1d1afe-e772-499f-9062-2bd3538a56d0", "")
            {
                _fermerInfo = new RepoItemInfo(this, "Fermer", "?/?/button[@accessiblename='Fermer']", 30000, null, "de48e2ba-0e3f-45de-9432-31d6448aced5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3f1d1afe-e772-499f-9062-2bd3538a56d0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3f1d1afe-e772-499f-9062-2bd3538a56d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Fermer item.
            /// </summary>
            [RepositoryItem("de48e2ba-0e3f-45de-9432-31d6448aced5")]
            public virtual Ranorex.Button Fermer
            {
                get
                {
                    return _fermerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Fermer item info.
            /// </summary>
            [RepositoryItemInfo("de48e2ba-0e3f-45de-9432-31d6448aced5")]
            public virtual RepoItemInfo FermerInfo
            {
                get
                {
                    return _fermerInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}